[[language]]
name = "python"
auto-format = true

[language.config.pylsp]
configurationSources = ["flake8"]
plugins.flake8.enabled = true
plugins.pycodestyle.enabled = false
plugins.pydocstyle.enabled = true
plugins.mccabe.enabled = false
plugins.pyflakes.enabled = false

[language.formatter]
command = "sh"
args = ["-c", "black --quiet - | isort -"]
