name: Publish

on:
  # workflow_run:
  #   workflows:
  #     - Test
  #   types:
  #     - completed
  #   branches:
  #     - main
  push:
    branches:
      - publish-pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and inspect package 
        uses: hynek/build-and-inspect-python-package@v1
  release-dev:
    environment: test-pypi
    if: github.ref == 'refs/heads/publish-pipeline'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download packages
        uses: actions/download-artifact@v3
        with:
          name: Packages
          path: dist
      - name: Upload to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
