name: Publish

on:
  # workflow_run:
  #   workflows:
  #     - Test
  #   types:
  #     - completed
  #   branches:
  #     - main
  push:
    branches:
      - publish-pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and inspect package 
      - uses: hynek/build-and-inspect-python-package@v1
